name: 葫芦侠签到

on:
    workflow_dispatch:
    schedule:
        - cron: "5 16 * * *"
    watch:
        types: [started]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: "初始化Python"
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'
                
            - name: "安装依赖包"
              run: pip install requests
     
            - name: "运行 葫芦侠"
              run: python3 huluxia.py
  
env:
     admin: ${{secrets.USER}} 
     psw: ${{secrets.PSW}}
     TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
     TG_USER_ID: ${{ secrets.TG_USER_ID }}
