name: huluxia

on:
    workflow_dispatch:
    schedule:
        - cron: "5 16 * * *"
    watch:
        types: [started]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: "初始化Python"
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'

            - name: "安装依赖包"
              run: pip install requests
                   pip install hashlib
                   pip install re

            - name: "运行 葫芦侠"
              run: python3 huluxia.py
  
env:
   key: ${{secrets.KEY}}
